### ISSUE TITLE
make run app is failing with this error

### ISSUE THREAD

**Issue by carlosmtobon** [allient/create-fastapi-project#4]
Python version 3.11.9
Poetry version 1.8.2
Make version 3.81

Running make install runs fine, but when running make run-app I get the following logs:

cd backend/app && poetry run uvicorn app.main:app --host 0.0.0.0 --port 8000 && cd ..
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Carlos\Desktop\my-python-env\Scripts\uvicorn.exe\__main__.py", line 7, in <module>
  File "C:\Users\Carlos\Desktop\my-python-env\Lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Carlos\Desktop\my-python-env\Lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Users\Carlos\Desktop\my-python-env\Lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Carlos\Desktop\my-python-env\Lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Carlos\Desktop\my-python-env\Lib\site-packages\uvicorn\main.py", line 409, in main
    run(
  File "C:\Users\Carlos\Desktop\my-python-env\Lib\site-packages\uvicorn\main.py", line 575, in run
    server.run()
  File "C:\Users\Carlos\Desktop\my-python-env\Lib\site-packages\uvicorn\server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Carlos\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "c:\Users\Carlos\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Carlos\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Carlos\Desktop\my-python-env\Lib\site-packages\uvicorn\server.py", line 69, in serve
    await self._serve(sockets)
  File "C:\Users\Carlos\Desktop\my-python-env\Lib\site-packages\uvicorn\server.py", line 76, in _serve
    config.load()
  File "C:\Users\Carlos\Desktop\my-python-env\Lib\site-packages\uvicorn\config.py", line 433, in load
    self.loaded_app = import_from_string(self.app)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Carlos\Desktop\my-python-env\Lib\site-packages\uvicorn\importer.py", line 22, in import_from_string
    raise exc from None
  File "C:\Users\Carlos\Desktop\my-python-env\Lib\site-packages\uvicorn\importer.py", line 19, in import_from_string
    module = importlib.import_module(module_str)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Carlos\AppData\Local\Programs\Python\Python311\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\Carlos\Desktop\gatekeeper-ai-assistant\backend\app\app\main.py", line 3, in <module>
    from app.api.v1.api import api_router as api_router_v1
  File "C:\Users\Carlos\Desktop\gatekeeper-ai-assistant\backend\app\app\api\v1\api.py", line 2, in <module>
    from app.api.v1.endpoints import (
  File "C:\Users\Carlos\Desktop\gatekeeper-ai-assistant\backend\app\app\api\v1\endpoints\chat.py", line 7, in <module>
    from app.utils.callback import (
  File "C:\Users\Carlos\Desktop\gatekeeper-ai-assistant\backend\app\app\utils\callback.py", line 3, in <module>
    from app.utils.chains import get_suggestions_questions
  File "C:\Users\Carlos\Desktop\gatekeeper-ai-assistant\backend\app\app\utils\chains.py", line 1, in <module>
    from langchain import LLMChain, PromptTemplate
  File "C:\Users\Carlos\Desktop\my-python-env\Lib\site-packages\langchain\__init__.py", line 36, in <module>
    from langchain.agents import MRKLChain, ReActChain, SelfAskWithSearchChain
  File "C:\Users\Carlos\Desktop\my-python-env\Lib\site-packages\langchain\agents\__init__.py", line 31, in <module>
    from langchain.agents.agent import (
  File "C:\Users\Carlos\Desktop\my-python-env\Lib\site-packages\langchain\agents\agent.py", line 15, in <module>
    from langchain.agents.agent_iterator import AgentExecutorIterator
  File "C:\Users\Carlos\Desktop\my-python-env\Lib\site-packages\langchain\agents\agent_iterator.py", line 30, in <module>
    from langchain.tools import BaseTool
  File "C:\Users\Carlos\Desktop\my-python-env\Lib\site-packages\langchain\tools\__init__.py", line 20, in <module>
    from langchain.tools.arxiv.tool import ArxivQueryRun
  File "C:\Users\Carlos\Desktop\my-python-env\Lib\site-packages\langchain\tools\arxiv\tool.py", line 9, in <module>
    from langchain.utilities.arxiv import ArxivAPIWrapper
  File "C:\Users\Carlos\Desktop\my-python-env\Lib\site-packages\langchain\utilities\__init__.py", line 25, in <module>
    from langchain.utilities.pubmed import PubMedAPIWrapper
  File "C:\Users\Carlos\Desktop\my-python-env\Lib\site-packages\langchain\utilities\pubmed.py", line 9, in <module>
    from pydantic_v1.class_validators import root_validator
ModuleNotFoundError: No module named 'pydantic_v1.class_validators'; 'pydantic_v1' is not a package
make: *** [run-app] Error 1

any ideas?

**Comment by vargasjona** [comment]
Hello @carlosmtobon Which template did you use?

**Comment by carlosmtobon** [comment]
It was the lang chain one template.
